"""Added image column to Post

Revision ID: 165d5505e8fc
Revises: 
Create Date: 2025-08-19 13:55:16.443971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d5505e8fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
